thirty_one_front:
    resource: "@ThirtyOneFrontBundle/Controller/"
    type:     annotation
    prefix:   /

thirty_one_member:
    resource: "@ThirtyOneMemberBundle/Controller/"
    type:     annotation
    prefix:   /

# FOSUser
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_login:
    path:   /connexion
    defaults:  { _controller: FOSUserBundle:Security:login }

fos_user_security_login:
    path:   /deconnexion
    defaults:  { _controller: FOSUserBundle:Security:logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profil

fos_user_profile_edit:
    path:   /compte/edition
    defaults:  { _controller: FOSUserBundle:Profile:edit }

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /compte/edition/pass

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messagerie