imports:
    - { resource: @ThirtyOneMemberBundle/Resources/config/security.yml }

security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }