security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/{_(profiler|wdt)}/
            security: false
        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /
                always_use_default_target_path: true
                default_target_path: /membre.html
            remember_me:
                key:      %secret%
                lifetime: 3000000000
                path:     /
                domain:   ~
            logout:       true
            anonymous:    true
